name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh -o StrictHostKeyChecking=no yahyaelrasit@34.22.250.82 "cd "